define({
    root: ({
      _widgetLabel: "Meteorology",
      header1: "Meteorological data layers",
      header2: "Wildfire weather",
      layer_weather: "Wind direction",
      layer_xdde: "Cloud-to-ground lightning (last 24h)",
      layer_xema: "Weather stations (XEMA)",
      layer_clima: "Climatic maps",
      layer_temp: "Temperature",
      layer_prec: "Precipitation",
      label_period: "Period",
      option_0: "Annual",
      option_1: "January",
      option_2: "February",
      option_3: "March",
      option_4: "April",
      option_5: "May",
      option_6: "June",
      option_7: "July",
      option_8: "August",
      option_9: "September",
      option_10: "October",
      option_11: "November",
      option_12: "December",
      info_text: "To obtain the data recorded during the date of a fire click on it and select the option '... Weather situation'",
      not_available_text: "Data not available for fires before 2009",
      table_temp: "Maximum temperature",
      table_prec: "Accumulated precipitation",
      table_hum: "Minimum relative humidity",
      table_wind: "Maximum wind intensity",
      text_station1: "Data from station ",
      text_station2: " during day",
      _featureAction_GetMeteo: "Weather situation"
    }),
    "ca": 1,
    "es": 1
  });