define({
    "_widgetLabel": "Meteorologia",
    "header1": "Capes d'informació meteorològica",
    "header2": "Situació meteorològica dels incendis",
    "layer_weather": "Valors actuals",
    "layer_xdde": "Llamps núvol-terra (darreres 24h)",
    "layer_xema": "Estacions meteorològiques (XEMA)",
    "layer_clima": "Mapes climàtics",
    "layer_temp": "Temperatura",
    "layer_prec": "Precipitació",
    "label_period": "Període",
    "option_0": "Anual",
    "option_1": "Gener",
    "option_2": "Febrer",
    "option_3": "Març",
    "option_4": "Abril",
    "option_5": "Maig",
    "option_6": "Juny",
    "option_7": "Juliol",
    "option_8": "Agost",
    "option_9": "Setembre",
    "option_10": "Octubre",
    "option_11": "Novembre",
    "option_12": "Desembre",
    "info_text": "Per obtenir les dades registrades durant la data d'un incendi clica sobre l'incendi i selecciona l'opció '... Situació meteorològica'",
    "not_available_text": "Dades no disponibles per a incendis anteriors al 2009",
    "table_temp": "Temperatura màxima",
    "table_prec": "Precipitació acumulada",
    "table_hum": "Humitat relativa mínima",
    "table_wind": "Intensitat màxima del vent",
    "text_station1": "Dades de l'estació ",
    "text_station2": " durant el dia ",
    "_featureAction_GetMeteo": "Situació meteorològica"
  });