define({
  "_widgetLabel": "Meteorología",
  "header1": "Capas de información meteorológica",
  "header2": "Situación meteorológica de los incendios",
  "layer_weather": "Valores actuales",
  "layer_xdde": "Rayos nube-tierra (últimas 24h)",
  "layer_xema": "Estaciones meteorológicas (XEMA)",
  "layer_clima": "Mapas climáticos",
  "layer_temp": "Temperatura",
  "layer_prec": "Precipitación",
  "label_period": "Periodo",
  "option_0": "Anual",
  "option_1": "Enero",
  "option_2": "Febrero",
  "option_3": "Marzo",
  "option_4": "Abril",
  "option_5": "Mayo",
  "option_6": "Junio",
  "option_7": "Julio",
  "option_8": "Agosto",
  "option_9": "Septiembre",
  "option_10": "Octubre",
  "option_11": "Noviembre",
  "option_12": "Diciembre",
  "info_text": "Para obtener los datos registrados durante la fecha de un incendio clica sobre el incendio i selecciona la opción '... Situación meteorológica'",
  "not_available_text": "Datos no disponibles para incendios anteriores al 2009",
  "table_temp": "Temperatura máxima",
  "table_prec": "Precipitación acumulada",
  "table_hum": "Humidad relativa mínima",
  "table_wind": "Intensidad máxima del viento",
  "text_station1": "Datos de la estación ",
  "text_station2": " durante el día ",
  "_featureAction_GetMeteo": "Situación meteorológica"
});